name: Start AI-agent

on:
  workflow_dispatch:  # Så du kan klicka "Run workflow"

jobs:
  call:
    runs-on: ubuntu-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installera beroenden
        run: pip install -r requirements.txt

      - name: Exportera miljövariabler
        run: |
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> $GITHUB_ENV
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> $GITHUB_ENV
          echo "MY_PHONE_NUMBER=${{ secrets.MY_PHONE_NUMBER }}" >> $GITHUB_ENV

      - name: Starta samtal
        run: python make_call.py
